### ISSUE TITLE
brew install dependency conflict docker/docker-edge

### ISSUE THREAD

**Issue by CygnusHyoga** [blaise-io/acelink#22]
Hi! with the recipe of brew, if you have installed docker-edge version the installation fail.
....
  depends_on cask: [
                     'vlc',
                     'docker',
                   ]
....

xx:~ xx$ brew cask list | grep docker
docker-edge
xx:~ xx$ 

Error:
xx$ brew cask install ace-link
==> Downloading https://github.com/blaise-io/acelink/releases/download/1.6.0/Ace
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'ace-link'.
==> Installing dependencies: docker
==> Downloading https://download.docker.com/mac/stable/45183/Docker.dmg
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'docker'.
==> Installing Cask docker
==> Purging files for version 2.3.0.2,45183 of Cask docker
Error: It seems there is already an App at '/Applications/Docker.app'.

Thanks!

**Comment by blaise-io** [comment]
This is an issue in `brew cask` (and please correct me if you know I'm wrong) because brew cask configs do not support an `or` statement in its `depends_on` directive. In your case it's probably easiest to install Ace Link manually if you don't want to switch to Docker stable. Ace Link will detect Docker to be installed if it is installed by brew cask.
