### ISSUE TITLE
Big Sur icon request

### ISSUE THREAD

**Issue by artexhibit** [blaise-io/acelink#30]
Hi Blaise.

Is it possible to add a Big Sur icon for AceLink or at least give us an .icns file to change it manually?

Thank you!

**Comment by blaise-io** [comment]
Hi @artexhibit, the source image for the icon can be found here: https://github.com/blaise-io/acelink/blob/master/Ace%20Link/Assets.xcassets/SVG.dataset/icon.svg. I believe you can adjust the image yourself using this trick https://superuser.com/questions/37811/ and you can convert SVG to ICNS using web services like https://www.converter365.com/vector-converter/svg/svg-to-icns. I currently don't have plans to update the app icon to match Big Sur's style, because the app is only visible in the menu bar where the Ace Link icon is up to date.

**Comment by artexhibit** [comment]
Thank you Blaise.

I will handle with it next. 

> I currently don't have plans to update the app icon to match Big Sur's style, because the app is only visible in the menu bar where the Ace Link icon is up to date.

You know, it was more like for my "perfectionist side" 😀

**Comment by artexhibit** [comment]
Created an .icns file. 

Decided to put the stuff here just in case if you or someone will need it: [Google Drive](https://drive.google.com/drive/folders/1ctl5tTLLzHcOes_mlNpmT7un3hT8aPsQ?usp=sharing)

**Comment by artexhibit** [comment]
> Google drive link is dead. I d like to have the icon if possible @artexhibit

It's live again: [Link](https://drive.google.com/file/d/1KSOecuArjExby5bzMzpWrwxqh_1MRE46/view?usp=sharing)

**Comment by takobaba** [comment]
Why dont you serve it on an icon host website, such as macosicons.com or somewhere?
