### ISSUE TITLE
Provide 10.12 version

### ISSUE THREAD

**Issue by pennal** [blaise-io/acelink#4]
I am running macOS 10.12.6, and I can't even open the project to compile it with a lower target. Is there any chance to lower the minimum target?

**Comment by blaise-io** [comment]
This is due to https://github.com/blaise-io/acelink/blob/master/Ace%20Link/AppDelegate.swift#L82mm which registers`acestream://` scheme support. It should compile when you remove the entire function, but you'll no longer able to launch Ace Link by opening an acestream:// URL, only by pasting an Ace Stream hash.

I'm new to coding Mac OS apps so I'm not sure how to make the code compatible with multiple Mac OS versions other than maintaining multiple branches. I'm open to suggestions.

**Comment by blaise-io** [comment]
I'm not going to fix this so I'm closing the issue. Ace Link 1.0.1 is the last macOS 10.12.x compatible version, you can download it here: https://github.com/blaise-io/acelink/releases/download/1.0.1/Ace.Link.1.0.1.dmg
