### ISSUE TITLE
V.2.0 only from history

### ISSUE THREAD

**Issue by Patriciooo** [blaise-io/acelink#44]
**Describe the bug**  
…  When open a new url a message say than no peers. Url in History worcking fine.

Note: Don't share AceStream IDs or websites containing pirated content.

**What I expected to happen**  
…Open news streams.

**Screenshots**  
…

**Additional debug info**  
… MacMini M1

**Comment by blaise-io** [comment]
I need some more info This is when clicking an `acestream://<hash>` link in a browser?

**Comment by Patriciooo** [comment]
It’s only happening some time. Safari and opening streaming from: https://acestreamsearch.net/en/?q=m.

Sorry but in holidays i dont try too much.

**Comment by 1w8uu** [comment]
In my case it was happening every time when clicking acestream://<hash> link in different browsers. However, these links did not show up in history, so I was not able to open it from there to try it.

**Comment by blaise-io** [comment]
@Patriciooo I removed your link because it contains pirated streams. 

I tried to reproduce the issue but it works for me in latest Firefox and Chrome with latest Ace Link.

In order to be able to debug this, can someone 

1. Open Console.app (part of default macOS install)
2. In the top-right corner of Console.app, filter by `Process`: `Ace Link`
3. In the toolbar located top-middle of Console.app, Click the `Start` button 
4. Now open an `acestream://` link in a browser and wait for Ace Link to show the "no peers" message
5. Go back to Console.app, ⌘+A, ⌘+C, ⌘+V to an email to blaisekal@gmail.com   
   or paste here but make sure to replace the ace stream hash if it's copyright protected content
 
Some guesses about the issue. 

1. For those getting a "no peers" message, maybe waiting 30 seconds is too low for some streams. [Can y'all please verify that using this build? It has a timeout of 120 seconds](https://github.com/blaise-io/acelink/files/7874672/Ace.Link.2.0.0-test.dmg.zip)
2. The stream is dead, please verify the exact same stream in 1.9.0

**Comment by Patriciooo** [comment]
Sorry. I use for open channels in Spain too. Sorry.

**Comment by nebelnic** [comment]
Experiencing the same issue. 
Some links in a browser show the "no peers" message with V2.0 and are streaming quickly with no issues, when rolled back to 1.9
(V2 is slower than 1.9 on my macbook air 2103 - catalina)

**Comment by artexhibit** [comment]
Same issue...

**Comment by blaise-io** [comment]
If anyone wants to help me solve this issue, take a look at https://github.com/blaise-io/acelink/issues/44#issuecomment-1013654745

**Comment by blaise-io** [comment]
![image](https://user-images.githubusercontent.com/788368/151546306-4863d39d-19d7-4d29-89a3-f84445bc8149.png)
