### ISSUE TITLE
How can I clear Acelink cache?

### ISSUE THREAD

**Issue by realrodri** [blaise-io/acelink#54]
How can I easily clean Acelink cache? I use VLC to reproduce videos, but can I somehow clear the cache Acelink makes? Also, I have no idea if Acelink makes any cache at all, and if it deletes it every time it's closed, but I want to make sure I can free up as many disk space as possible.

Thanks!

**Comment by blaise-io** [comment]
Ace Link cache is removed when you stop or restart a stream, or when you quit Ace Link.

**Comment by realrodri** [comment]
> Acestream cache is removed when you stop or restart a stream, or when you quit Ace Link.

Sounds good, but good can I make sure it does?

**Comment by blaise-io** [comment]
Happens automatically. Docker container is restarted for each stream, Docker container is started with `--rm` flag. Search for it in the source code.

**Comment by realrodri** [comment]
> Happens automatically. Docker container is restarted for each stream, Docker container is started with `--rm` flag which throws away all data after running. Search for that flag in the source code.

Awesome! Thank you for the clarification :)

**Comment by Albertuso** [comment]
i asked the same question, but didn´t know exactly how it´s working, i just checked than restarting the mac the space came back avaiable again. This is usefull for people like me than installed mac on the ssd of the fusion drive and another tip that i can give is that is possible use it for people who doesn´t want to change to zsh instead of bash (i mean people who doesn´t go further to mojave) injecting code to the kernel. You can use it but you need to install docker version 2.5 not the latest one because it wont be run, and works perfectly because the others options left work few months ago
